"use client";

import { MapPin, Calendar, Compass } from "lucide-react";
import Link from "next/link";
import { mockDestinations } from "@/data";

export default function DashboardTrips() {
  return (
    <div className="p-4 md:p-8 space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4 mb-2">
        <div>
          <h1 className="text-3xl font-bold">Planned Trips</h1>
          <p className="text-foreground/60">View and manage the itineraries generated by your AI agent.</p>
        </div>
        <Link href="/plan" className="px-4 py-2 bg-primary text-white rounded-xl font-bold hover:bg-primary-dark transition-colors">
          + Generate New Itinerary
        </Link>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 pt-4">
        {mockDestinations.slice(0, 4).map((dest) => (
          <div key={dest.id} className="bg-background rounded-3xl border border-foreground/10 shadow-sm overflow-hidden flex flex-col md:flex-row group hover:shadow-md transition-shadow">
            <div className="h-48 md:h-auto md:w-2/5 overflow-hidden shrink-0 relative">
               {dest.imageUrl && <img src={dest.imageUrl} alt={dest.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" />}
               <div className="absolute inset-0 bg-gradient-to-t from-background/90 to-transparent md:hidden" />
               <span className="absolute top-3 left-3 px-2 py-1 bg-white/20 backdrop-blur-md rounded-full text-[10px] font-bold uppercase text-white shadow-sm border border-white/20">
                 Draft Mode
               </span>
            </div>
            
            <div className="p-6 flex-1 flex flex-col justify-between">
               <div>
                  <h3 className="text-2xl font-bold leading-tight mb-2 group-hover:text-primary transition-colors">{dest.name}</h3>
                  <div className="flex items-center gap-1 text-sm text-foreground/60 font-medium mb-4">
                    <MapPin className="w-4 h-4 text-primary" /> {dest.location}
                  </div>
                  <p className="text-foreground/70 text-sm line-clamp-2">{dest.description}</p>
               </div>
               
               <div className="mt-6 pt-4 border-t border-foreground/10 flex justify-between items-center w-full">
                  <div className="flex items-center gap-2 text-sm font-bold text-foreground/50">
                     <Calendar className="w-4 h-4" /> Not Scheduled
                  </div>
                  <Link href={`/details/${dest.id}`} className="flex items-center gap-1 text-sm font-bold text-primary hover:underline">
                    <Compass className="w-4 h-4" /> Open Plan
                  </Link>
               </div>
            </div>
          </div>
        ))}
      </div>
      
    </div>
  );
}
